trigger:
  branches:
    include:
      - main

pool:
  vmImage: "ubuntu-latest"

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: "3.x"
      addToPath: true

  - script: |
      python -m venv venv
      source venv/bin/activate
      pip install -r server/requirements.txt
    displayName: "Install dependencies"

  - script: |
      source venv/bin/activate
      cd client
      npm ci
      npm run build
    displayName: "Build React frontend"

  - script: |
      source venv/bin/activate
      python -m pip install --upgrade pip setuptools wheel
      pip install gunicorn
    displayName: "Install Gunicorn"

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: "$(Build.SourcesDirectory)"
      includeRootFolder: false
      archiveType: "zip"
      archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      replaceExistingArchive: true

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: "$(Build.ArtifactStagingDirectory)"
      artifactName: "drop"
      publishLocation: "Container"
